image: docker:stable

services:
  - docker:dind

build:
  stage: build
  variables:
    DOCKER_IMAGE_TAG: "eu.gcr.io/${PROJECT_ID}/${APP_NAME}"
  script:
    - docker build -t "${DOCKER_IMAGE_TAG}" .
    - echo "${SERVICE_ACCOUNT_KEY}" > key.json
    - docker login -u _json_key --password-stdin https://eu.gcr.io < key.json
    - docker push ${DOCKER_IMAGE_TAG}
  only:
    - master

deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  script:
    - apk add gettext
    - gcloud components install kubectl
    - envsubst < ./k8s/${APP_NAME}-deployment.tmp.yaml > ./k8s/${APP_NAME}-deployment.yaml
    - envsubst < ./k8s/${APP_NAME}-service.tmp.yaml > ./k8s/${APP_NAME}-service.yaml
    - echo "${SERVICE_ACCOUNT_KEY}" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project ${PROJECT_ID}
    - gcloud config set container/cluster ${CLUSTER_NAME}
    - gcloud config set compute/zone europe-west2-a
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west2-a
    - kubectl apply -f k8s/${APP_NAME}-deployment.yaml
    - kubectl apply -f k8s/${APP_NAME}-service.yaml
  only:
    - master
