image: docker:stable

services:
  - docker:dind

build:
  stage: build
  variables:
    DOCKER_IMAGE_TAG: "eu.gcr.io/${PROJECT_ID}/${APP_NAME}"
  artifacts:
    paths:
      - sha256.txt
    untracked: true
    expire_in: 2 days
  script:
    - echo "${SERVICE_ACCOUNT_KEY}" | docker login -u _json_key --password-stdin https://eu.gcr.io
    - docker pull "${DOCKER_IMAGE_TAG}:latest"
    - docker build --cache-from ${DOCKER_IMAGE_TAG:latest} -t "${DOCKER_IMAGE_TAG}:${CI_COMMIT_SHA}" -t "${DOCKER_IMAGE_TAG}:latest" .
    - docker push "${DOCKER_IMAGE_TAG}:${CI_COMMIT_SHA}"
    - docker push "${DOCKER_IMAGE_TAG}:latest"
    - docker inspect --format='{{index .Id }}' "${DOCKER_IMAGE_TAG}:${CI_COMMIT_SHA}" > sha256.txt
  only:
    - master

deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  script:
    - apk add gettext
    - gcloud components install kubectl
    - export SHA256=$(cat sha256.txt)
    - envsubst < ./k8s/${APP_NAME}-deployment.tmp.yaml > ./k8s/${APP_NAME}-deployment.yaml
    - envsubst < ./k8s/${APP_NAME}-service.tmp.yaml > ./k8s/${APP_NAME}-service.yaml
    - echo "${SERVICE_ACCOUNT_KEY}" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project ${PROJECT_ID}
    - gcloud config set container/cluster ${CLUSTER_NAME}
    - gcloud config set compute/zone europe-west2-a
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west2-a
    - kubectl apply -f k8s/${APP_NAME}-deployment.yaml
    - kubectl apply -f k8s/${APP_NAME}-service.yaml
  only:
    - master
