image: docker:stable

services:
  - docker:dind

build:
  stage: build
  variables:
    DOCKER_IMAGE_TAG: "eu.gcr.io/portfolio-230113/simple-counter"
  script:
    - docker build -t "${DOCKER_IMAGE_TAG}" .
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - docker login -u _json_key --password-stdin https://eu.gcr.io < key.json
    - docker push ${DOCKER_IMAGE_TAG}
  only:
    - master

deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project portfolio-230113
    - gcloud config set container/cluster portfolio-apps
    - gcloud config set compute/zone europe-west2-a
    - gcloud container clusters get-credentials my-cluster --zone europe-west2-a
    - kubectl apply -f k8s/simple-counter-deployment.yaml
    - kubectl apply -f k8s/simple-counter-service.yaml
  only:
    - master
