apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-counter
  template:
    metadata:
      labels:
        app: simple-counter
    spec:
      containers:
        - name: simple-counter-app
          image: eu.gcr.io/portfolio-230113/simple-counter@sha256:c0b847c4ff3053b79c5efa94e67f32d07780c39b1a6fad47786ce6f208bd9378
          resources:
            requests:
              cpu: "25m"
